UseOROCOS-RTT-helpers.cmake
UseOROCOS-RTT.cmake

The first patch extends and simplifies the DESTDIR support introduced in 85fc9d3. It should have no effect on normal builds where the DESTDIR environment variable is not set.
The original patch assumed that DESTDIR is already set during the configure step, like with
```
DESTDIR=/tmp/destdir catkin_make_isolated --install ...
```
In a pure catkin workspace, packages can be built for a whole workspace with a standard debian/rules file and debhelper's support for the cmake build system. In this case DESTDIR is only set during the install step
and the previous patch was not effective, causing RPATH-related errors during runtime.
The INSTALL_RPATH is still constructed based on the information from the pkg-config files for packages in *overlayed* workspaces or system packages. Additionally, …

Extended DESTDIR support for packages built in the same workspace

---

rtt/extras/FileDescriptorActivity.cpp
rtt/extras/FileDescriptorActivity.hpp
tests/specialized_activities.cpp

A pipe in Linux seems to have a limited buffer size of 65536 bytes. Every trigger() has written a command byte to the pipe to wake up the thread and the loop() function empties the command before each step() invocation. For the case the step takes too long, commands could queue up and after the pipe is full the write() system call has blocked the thread that triggered the FileDescriptorActivity.
This patches makes the command pipe non-blocking and adds additional flags to the FileDescriptorActivity to make sure that we never miss a command event even if the queue was full.
The patch does not support Windows as it requires the fcntl  system call setting the `O_NONBLOCK` flag for the command pipe. In Windows the behavior is unchanged.

Fixed blocking trigger() calls on FileDescriptorActivities if the step() function takes too long

---

rtt/os/Timer.cpp
rtt/os/Timer.hpp
tests/time_test.cpp

This is needed for the implementation of `OCL::TimerComponent::wait()` and `OCL::TimerComponent::waitFor()`.
See orocos-toolchain/ocl#23 and orocos-toolchain/ocl#24.

Added os::Timer::waitFor(...) and os::Timer::waitForUntil(...… …) member functions

---

rtt/transports/corba/TaskContextProxy.cpp
rtt/transports/corba/TaskContextProxy.hpp

This is useful if a derived class wants to initialize the
typekits, before initializing the proxy itself.
The current usecase is the orogen cpp proxy layer, were
proxies for tasks are generated. In this case we want to
initialize the typekit for the task in the constructor of the 
orogen-proxy before synchronizing.

Allow the construction of an uninitialized TaskContextProxy

---

rtt/extras/FileDescriptorActivity.cpp

This is a follow-up and minor cleanup of pull request #78.
The missing initializers had no effect as these boolean flags are reset in start() anyway.

extras: added missing initializers to one of the FileDescriptorActivity constructors and fixed compiler warnings with -Wunused-result

---

UseOROCOS-RTT.cmake

This removes ROS generated messages from the exported libraries that
might cause issues when auto-linking is enabled.

prevent ROS generated messages linking

---

config/check_depend.cmake
rtt/os/targets/target-config.h.in
rtt/transports/corba/TaskContextServer.cpp

A component that acts as a COBRA server, but that is not registering with the name
service, will cause an IOR to be output to the deployer console and the IOR to
be written to a file in PWD. This behaviour is not desirable in all applications.
This patch makes the behaviour optional in RTT, by providing a global option to
disable the IOR emission (defaults to OFF, to keep backwards compatibility).
When not emitting then the IOR is not written to stdout nor to file.

corba: Optionally support not emitting IORs if name service not used

---

UseOROCOS-RTT-helpers.cmake

Use case: to build CORBA typekits you need the full path to the /include/orocos//transports/corba,
as the include_dirs might consist of multiple paths, include_dirs cannot be used for this purpose. The prefix path can
be used instead in this use-case.
Signed-off-by: Ruben Smits <ruben.smits@intermodalics.eu>

cmake: also export the package install prefix

---

config/rtt_macros.cmake

This makes sure that depending projects link with the major.minor version instead of the full version typekit/plugin.
E.g.
````
ldd bin/deployer-gnulinux 
...
liborocos-rtt-gnulinux.so.2.8 => /home/rsmits/orocos_ws/install_isolated/lib/liborocos-rtt-gnulinux.so.2.8 (0x00007f05daa7d000)
liborocos-ocl-log4cpp-gnulinux.so.2.8.0 => /home/rsmits/orocos_ws/install_isolated/lib/liborocos-ocl-log4cpp-gnulinux.so.2.8.0 (0x00007f05da9f6000)
liborocos-ocl-taskbrowser-gnulinux.so.2.8.0 => /home/rsmits/orocos_ws/install_isolated/lib/liborocos-ocl-taskbrowser-gnulinux.so.2.8.0 (0x00007f05da9be000)
liborocos-ocl-deployment-gnulinux.so.2.8.0 => /home/rsmits/orocos_ws/install_isolated/lib/liborocos-ocl-deployment-gnulinux.so.2.8.0 (0x00007f05da7be000)
...
librtt-scripting-gnulinux.so.2.8.0 => …
```

cmake: add SOVERSION for typekits and plugins

---

rtt/os/ecos/fosi.h
rtt/os/lxrt/fosi.h
rtt/os/xenomai/fosi.h

Fix for #106.
The constants `ORO_WAIT_REL` and `ORO_WAIT_ABS` are not available if RTT is compiled for the Xenomai target.

Added ORO_WAIT_ABS and ORO_WAIT_ABS constants for all targets

---

rtt/extras/FileDescriptorActivity.hpp
rtt/extras/FileDescriptorActivityInterface.hpp
rtt/extras/FileDescriptorSimulationActivity.cpp
rtt/extras/FileDescriptorSimulationActivity.hpp

Any component using an FDA is explicitly coupled to the FDA activity type (i.e. it can't use Activity) as the component has to know why it was woken up, which means querying the activity object directly (for example, being woken up by a signal causes the component to process data, but being woken by a timeout causes the component to take some safety action). Because the FDA has to be queried, this creates a run-time type dependency of the component on its Activity (i.e. it *requires* an FDA as its activity as it needs to query the FDA interface - these functions (e.g. hasTimeout()) are not present in the base Activity class). Hence the component can only be instantiated with an FDA - it won't accept any other Activity type.
Our unit test cases do cycle-by-cycle checks of such component's …

Can't deterministically control execution of components in a unit test that explicit depend on FileDescriptorActivity.

---

tests/corba_ipc_server.cpp
tests/corba_mqueue_ipc_server.cpp

This is a regression from 180e6905c43cb23a76f588783179e14ff5071caf that causes the corba-ipc-server and corba-mqueue-ipc-server processes to segfault if real-time memory allocation is enabled (the default if TLSF is available).

tests: fixed typos in corba and mqueue ipc tests that caused segfaults

---

rtt/scripting/StateMachine.cpp

This is a follow-up of 6537ae7736ba887c25642f76ac96081d04039c5e that was merged in #64. Some pointer checks were missing.
This patch is completely untested! I don't even know at the moment why the current pointer can be NULL in this method, but this is obviously the reason for the previous PR.

scripting: added missing zero-pointer checks in StateMachine::executePending()

---

rtt/base/PortInterface.cpp
rtt/base/PortInterface.hpp
rtt/internal/ConnFactory.hpp
rtt/internal/ConnectionManager.cpp
rtt/internal/ConnectionManager.hpp
tests/ports_test.cpp

These new tests run 4 threads each. Two of them are continuously writing to and reading from an OutputPort/InputPort pair, while the other two connect and disconnect an additional OutputPort and an additional InputPort to these ports, respectively.
The four test cases cover the four different connection layouts introduced with the updated-dataflow-semantics branch (see #114).

Added test suite to test connecting and disconnecting ports concurrently

---

rtt/TaskContext.cpp
rtt/TaskContext.hpp
rtt/base/BufferBase.hpp
rtt/base/BufferLockFree.hpp
rtt/base/BufferLocked.hpp
rtt/base/BufferUnSync.hpp
rtt/base/ChannelElementBase.hpp
rtt/base/ChannelInterface.cpp
rtt/internal/ChannelBufferElement.hpp
rtt/internal/ChannelDataElement.hpp
rtt/internal/ConnInputEndPoint.hpp
rtt/internal/ConnOutputEndPoint.hpp
rtt/internal/ConnectionManager.hpp
rtt/transports/corba/RemoteChannelElement.hpp
rtt/transports/mqueue/MQChannelElement.hpp

Hey, 
I did a proof of concept implementation of the concept we talked
about on the mailing list. These are the modification to rtt that are 
needed to implement the Introspection ability. Please note, that
we would also need to patch the RosPubChannelElement in order
to make it work with the ROS transport. 
Note, this is a POC, it is not intended for direct merging.
I also have a client side implementation for this, which can be found
here :
https://github.com/jmachowinski/rtt_introspection
https://github.com/jmachowinski/rtt_introspection_typekit
As it is still a proof of concept it is not tidied up and hacky....
The output of it looks like this :
Task task2
Output Ports : 
output2 :
Connections
ConnInputEndpoint(0x7fe53800b7f0)->ChannelDataElement(0x7fe53800b780)->CorbaRemoteChannelElem …

Second Introspection implementation

---

rtt/os/Timer.cpp
rtt/os/gnulinux/fosi_internal.cpp

I'm not confident the proposed behavior is desired, I'm looking for comments/feedback.
I had the case with system time changed after rtt started, it caused all the periodic activities and timer to
run continuously to catch up all the missing updates since 1970.
I think the similar situation may happen when the system clock changed for other reasons like
daylight or time zone changes.
The better solution would be to use monotonic clocks, but as I understand it can't be used with sem_timedwait.

Skip task/timer updated if late for more than a few periods

---

rtt/os/gnulinux/fosi_internal.cpp

It simplifies debugging and allows to associate threads
with tasks/activities

Set thread name to match activity name on linux

---

rtt/TaskContext.cpp

Build fails when configured to use sequential activity by default, trivial fix

Fixed build when sequential activity is used by default

---

rtt/transports/mqueue/MQSendRecv.cpp
tests/corba_ipc_server.cpp
tests/corba_ipc_test.cpp
tests/corba_mqueue_ipc_server.cpp
tests/corba_mqueue_ipc_test.cpp

There was a regression in the mqueue transport from https://github.com/orocos-toolchain/rtt/commit/a34a19ad740fc15a81574ade66c5266fdf340576. The inputReady() call on the receiving side of the channel did not block anymore on the data sample being received and therefore the `corba_mqueue_ipc_test` can fail depending on the number of CPUs available and load.
Furthermore I improved both tests that involve IPC, the `corba_ipc_test` and `corba_mqueue_ipc_test` to be more resilient against execution under high CPU load or on slow machines. Additionally, a `resetCallBackPeer()` method has been introduced in order to allow multiple executions of the test (the client) against the same running server process.
This PR will hopefully fix the [test errors on …

Fix mqueue transport and corba ipc tests

---

config/FindTAO.cmake
rtt/transports/corba/CMakeLists.txt
rtt/transports/corba/CorbaLib.cpp
rtt/transports/corba/CorbaOperationCallerFactory.cpp
rtt/transports/corba/CorbaTemplateProtocol.hpp
rtt/transports/corba/CorbaTypeTransporter.hpp
rtt/transports/corba/DataFlow.idl
rtt/transports/corba/DataFlowI.cpp
rtt/transports/corba/DataFlowI.h
rtt/transports/corba/RemoteChannelElement.hpp
rtt/transports/corba/RemotePorts.cpp
rtt/transports/corba/Service.idl
rtt/transports/corba/ServiceRequester.idl
rtt/transports/corba/rtt-corba-config.h.in

This PR adds some patches that fix the behavior of the CORBA transport in the toolchain-2.9 branch, which is a merge of various features, especially the efficiency patches (#123) and the updated dataflow semantics (#114).
The first commit 63218b0 fixes an issue that broke the proper cleanup after one end of a CORBA connection terminates or crashes. Now the `RemoteChannelElement::write()` call would return the WriteStatus `NotConnected` and thus indirectly, via the dispatcher, cause the writing side to remove the connection from the port. This is basically the behavior of RTT versions before 2.9. It is up to the user to eventually reestablish broken connections if the port's write call returns `NotConnected` in case this is required.
The second commit f69a0b7 reintroduces the standard …

corba: revert oneway writes and fixed connection cleanup and TAO builds

---

rtt/transports/corba/RemotePorts.cpp
rtt/transports/corba/RemotePorts.hpp
tests/corba_test.cpp

Disconnect from certain port.
Implementing the previous missing function to disconnect RTT::corba::RemoteOutputPort and RTT::corba::RemoteInputPorts from a certain given remote port.
(instead of disconnect all).

Implement CORBA disconnect(port).

---

rtt/types/SequenceTypeInfoBase.cpp

This PR adds the missing implementation of specialized method `RTT::types::get_container_item_copy(const std::vector<bool> & cont, int index)` required by `SequenceTypeInfo<T>` implementation for type `std::vector<bool>`.
The default RTT typekit does not contain type `std::vector<bool>` and therefore does not trigger this error.

Fixed typekit for bool sequences

---

rtt/base/BufferLockFree.hpp

The missing check of the return value of `bufs.dequeue()` let the buffers_test fail from time to time under high CPU load because of memory pool corruption due to double deallocation.
Merged to toolchain-2.9 in https://github.com/orocos-toolchain/rtt/commit/dcc7df5dd7685b167f337e29a8fb99000c757f84.

Fixed potential double deallocation and pool corruption for circular BufferLockFree

---

rtt/types/TypeInfoRepository.cpp
rtt/types/TypeInfoRepository.hpp

This commit adds the option, to load typekits on demand.
This is especially useful, if one uses RTT::corba::TaskContexProxy,
as the ports are not reported, if no typekit for them is present.

Added option, to load typekits on demand

---

rtt/types/PropertyComposition.cpp
tests/property_composition_test.cpp

The method `types::decomposePropertyBag()` did not retain the type of the PropertyBag returned by `types::TypeInfo::decomposeType()` for each individual property and therefore the subsequent composition did not recognize the original type. For example, the KDL typekit implements composition and decomposition using that method (in [kdlTypekit.hpp:163](https://github.com/orocos/rtt_geometry/blob/indigo-devel/kdl_typekit/src/kdlTypekit.hpp#L163) and [motionproperties.cpp:380ff.](https://github.com/orocos/rtt_geometry/blob/indigo-devel/kdl_typekit/src/motionproperties.cpp#L380)). The fallback method of property decomposition implemented in `types::propertyDecomposition()` using `getMember()` is not affected by this issue and sets the type of the target bag correctly.
The updated test in RTT …

Fixed decomposition of PropertyBags which contain types that implement the TemplateCompositionFactory interface

---

rtt/Property.hpp
rtt/base/PropertyBase.hpp
tests/property_test.cpp

These new methods can be used to "link" a property to another without having to know the exact derived type, e.g.:
```cpp
bool linkProperty(RTT::base::PropertyBase *target,
const RTT::base::PropertyBase *source) {
return target->setDataSource(source->getDataSource());
// or
*target = source;
return target.ready();
}
```
```cpp
// create another property b which mirrors a
RTT::Property<double> a("a", "example property", 5.0);
RTT::PropertyBase *b = a->create();
*b = a;  // or linkProperty(b, &a)
assert(b.getDataSource() == a.getDataSource());
```
It should be noted that the assignment `*b = a` in the above example is equivalent to `b = a->copy()` because `PropertyBase::copy()` introduced in 44b9970e9685b9b812ddce1e8cc8c9b400553d54 also has linking semantics (shared data source). This is in …

Added method setDataSource() and assignment operator to the PropertyBase interface

---

rtt/internal/ConnectionManager.hpp

This is a slight optimization of reader channel selection in class ConnectionManager, avoiding to read from the current channel twice.
Reading from a channel might be expensive, e.g. for remote connections. The reader channel selection always tries to read from the current channel (the one with the last successful read) first. There is no need to read that channel again while iterating over all channels for the case that first read did not return new data.
If have not tested this very carefully yet, but at least all the tests succeed. I do not see any use case where this patch would break things. On the other hand it is certainly an improvement when reading from input ports connected to remote output ports with a pull policy.

Slight optimization of reader channel selection for input ports

---

rtt/os/ecos/fosi_internal.cpp
rtt/os/gnulinux/fosi_internal.cpp
rtt/os/lxrt/fosi_internal.cpp
rtt/os/macosx/fosi_internal.cpp
rtt/os/win32/fosi_internal.cpp
rtt/os/xenomai/fosi_internal.cpp

The destructor of class `RTT::os::Thread` calls the `getName()` method for logging, which forwards to `rtos_task_get_name()`, but the memory that holds the thread name has already been freed at that point. This patch should fix this problem for all target types, but I only tested it for gnulinux so far.

Fixed invalid read of freed thread name in os::Thread destructor

---

rtt/rtt-config.h.in

This pull request is part of a bigger effort to add support for new connection semantics to RTT (see #114).
The version comparison macro allows dependees to add sections that are compiled conditionally based on the RTT version used. Unfortunately this cannot be avoided in same cases, primarily for custom transport implementations like [rtt_roscomm](https://github.com/orocos/rtt_ros_integration/tree/HEAD/rtt_roscomm).
As the updated dataflow implementation is targeted for an RTT 2.9 release and the intermediate version number has already been increased to 2.8.99, the typical use case of this macro would be like:
```cpp
#include <rtt/rtt-config.h>
#ifdef RTT_VERSION_GTE(2,8,99)
// code that requires the new dataflow implementation
#else
// backwards compatible code for older versions of RTT …
```

Added version comparison macro

---

rtt/transports/corba/DataFlow.idl
rtt/transports/corba/RemoteChannelElement.hpp

Signal order does not matter, so we can safely use oneway.
This "unblocks" the CORBA dispatchers on pull connections, something I always assumed had been fixed a while ago (I remember a patchset to avoid signalling pull connections that are not going to an event port). The latter would have been a better solution, but this is really a low-hanging fruit with great effect.

corba: use oneway for signalling the remote on pull channels

---

rtt/os/gnulinux/fosi_internal.cpp

See http://www.orocos.org/forum/orocos/orocos-users/orocosusers-getting-permission-denied-deployers-after-running-setcap-soem.
Fixed regression from bc05dceed2f123c35893bf0033d7257373f2f605.
A failure the set the name of the thread should not lead to the termination of the process.

Do not abort if pthread_setname_np fails

---

rtt/TaskContext.cpp
rtt/TaskContext.hpp

This PR reverts commits 9011cf9615dfdd6db02c4781c9bd38de76ebad12 and 9c9e008f74d87e4b352d0294f5bda47b1c1550ef from #90, that add a `loadPlugin()` operation to the TaskContext interface.
Alternative solutions are:
- use a remote proxy for the DeploymentComponent (the `import()` operation is doing exactly the same)
- add the `loadPlugin()` operation to one application-specific subclass instead of to the base class `TaskContext`
It should be noted that there is a difference between loading a plugin (in the process) and loading a service (in a component or in the global service). Plugins can provide a service, but they can also provide typekits, transports or do something completely different. And of top of that there are packages, which are basically collections of component libraries and/or …

Revert "added ability to load a plugin using a operation on a task."

---

CMakeLists.txt
env-hooks/00.rtt.sh.in

The env-hook sets the OROCOS_TARGET environment variable if not set and adds the lib/orocos directory of the install-space and all entries of the CMAKE_PREFIX_PATH (for catkin workspaces) to the
RTT_COMPONENT_PATH.
The scripts in etc/orocos/OROCOS_TARGET/profile.de will be sourced in lexical order by a new [setup.sh](https://github.com/meyerj/orocos_toolchain/blob/installation-script/setup.sh)
script located in the orocos_toolchain repository.

env-hooks: install env-hook to etc/orocos/OROCOS_TARGET/profile.d

---

rtt/os/macosx/fosi.h

It appears that recent updates to Xcode make the compiler more wary ... fix the resulting errors. Tested with Xcode 8.2.1 on OS X 10.11

macosx: Add static casts to slience C++11 narrowing errors

---

rtt/transports/mqueue/binary_data_archive.hpp
rtt/types/carray.hpp
rtt/types/type_discovery.hpp
tests/mqueue_archive_test.cpp

Partial Function Template Ordering was removed from boost in 1.59, the according define BOOST_PFTO also.
I am not really sure if the define is the correct way to solve it, bur at lease the functionality doesn't change for users with older boost versions
Also changed some ifdefs, from checking against 1.62 to 1.61 (current default in ubuntu 16.10)
I wonder how it compiled against 1.62 before, somebody might have done it as the boost::serialization::array_wrapper defines were already here

boost 1.61 support

---

rtt/internal/ConnectionManager.cpp
rtt/internal/ConnectionManager.hpp

The ConnectionManager is responsible for selecting the next channel to read if an InputPort has multiple connections, which are managed in a list of `ChannelDescriptor` instances. The `ChannelDescriptor` contains the ConnPolicy of the connection, which in turn contains a `std::string` element `name_id`. Copying `ChannelDescriptor` instances is therefore not real-time safe. Luckily it is not required and we can work with a pointer (or iterator) to the current channel.
It should be noted that most implementations of `std::string` usually do not reallocate once its internal buffer is big enough to hold all potential values (all `name_id`s of connected channels). So the risk that reassigning the `std::string` element in `cur_channel` is causing heap allocations in critical paths is quite …

Fixed potential memory allocation problem in ConnectionManager

---

rtt/ExecutionEngine.cpp
rtt/base/TaskCore.cpp
tests/taskstates_test.cpp

stop() does a synchronization point by stopping the activity, but
then starts it right away. Given that the EE was not checking against
mTargetState when deciding to call errorHook(), there was a chance
that errorHook was called during or after stopHook.
Moreover, while error() was checking that mTargetState was a runtime
state, recover() was not, which could lead to a call to recover()
overriding mTargetState during the stop, leaving the task stopped
but in an inconsistent state.
The tests loop because of the racy nature of the problem. On my machine,
with the timing setup and 100 tries, I was getting more than 50% hits.

fix race conditions between stop() and the runtime error state

---

tests/taskthread_fd_test.cpp

`BOOST_CHECK_CLOSE_FRACTION(left, right, tolerance)` expects a tolerance given as fraction of absolute values (http://www.boost.org/doc/libs/1_62_0/libs/test/doc/html/boost_test/utf_reference/testing_tool_ref/assertion_boost_level_close_fraction.html).
With the introduction of additional sleep delay of half a timeout cycle the timeout counter should be predictable enough for exact checks. However the checks could fail if the CPU is too busy to execute the FileDescriptorActivity.

tests: fixed timeout counter expectations in FileDescriptorActivity tests

---

rtt/plugin/PluginLoader.cpp

... as this might trigger the creation of a new Logger instance during static destruction.

plugin: do not log during destruction of the PluginLoader singleton

---

rtt/transports/corba/RemotePorts.hpp

This is a minor regression from https://github.com/orocos-toolchain/rtt/pull/142/commits/0db4e04b4cbaac2218f0d2a38a90671407d14f45 (#142).
Declaring `bool disconnect(PortInterface* port)` in `RemoteInputPort` and `RemoteOutputPort` without a using directive hides the overload `void RemotePort<PortClass>::disconnect()`. The classes are almost exclusively used internally and apparently this code path was not triggered.

corba: fixed hidden overloaded virtual functions in RemotePorts.hpp

---

rtt/internal/FusedFunctorDataSource.hpp
rtt/internal/OperationInterfacePartFused.hpp

The [Boost unfused adapter](http://www.boost.org/doc/libs/1_58_0/libs/fusion/doc/html/fusion/functional/adapters/unfused.html) accepts only LValue arguments, while in general operations can also have RValues as arguments (const references or temporaries). Without C++11 or for older Boost versions this was apparently not an issue and the necessary conversion have been done implicitly (?).
The solution applies the [forward_adapter template](http://www.boost.org/doc/libs/1_63_0/libs/functional/forward/doc/html/index.html) to overcome this limitation as suggested in the Boost Fusion documentation.
This patch also reverts the `USE_CPP11` macro usage for this file, as it did not use `std::bind` or any other C++11 feature anyway and the only effect was the namespace of placeholders (see …

Fixed OperationInterfacePartFused for -std=c++11 builds with Boost 1.58 (master)

---

rtt/internal/BindStorage.hpp
rtt/internal/CreateSequence.hpp
rtt/internal/FusedFunctorDataSource.hpp
rtt/internal/OperationInterfacePartFused.hpp

Like #196, but targets toolchain-2.9 and includes some other related patches that only apply to toolchain-2.9.

Fixed OperationInterfacePartFused for -std=c++11 builds with Boost 1.58 (toolchain-2.9)

---

rtt/transports/corba/CorbaConversion.hpp

Required to convert vectors and maps that have a custom allocator, e.g. `RTT::os::rt_allocator<T>`.

corba: added template arguments Alloc and Compare for RTT::corba::AnyConversion specializations for vectors and maps

---

rtt/types/PropertyDecomposition.cpp
tests/corba_ipc_test.cpp
tests/corba_test.cpp
tests/ports_test.cpp
tests/specialized_activities.cpp

auto_ptr was deprecated in C++11. Removes compiler warnings when compiling with `-std=c++11`.
See http://en.cppreference.com/w/cpp/memory/auto_ptr.

Replaced all occurences of deprecated auto_ptr by unique_ptr

---

tests/dev_test.cpp

`DigitalInput` expects a `const bool &` in its constructor and stores it in a member variable. The dev_test passed a boolean literal, but C++ creates a temporary in this case which is only valid during the call.
At least with gcc 5 the dev_test consistenly failed:
```
/home/travis/build/orocos-toolchain/rtt/tests/dev_test.cpp(56): error in "testClasses": check din.isOn() failed
```
See https://travis-ci.org/orocos-toolchain/rtt/jobs/192398795.

tests: fixed dev_test for gcc 5

---

rtt/Service.cpp
rtt/ServiceRequester.cpp
rtt/TaskContext.cpp

Fixes the service destruction bug as reported in https://github.com/orocos-toolchain/rtt/issues/179. We should clear() the tasks service and requester interface on TaskContext destruction to not prevent destruction of children unless they are still referenced from somewhere else.
Includes https://github.com/psoetens/rtt/pull/8, but adds a commit which recursively resets the owner pointer of all children in case there is still another reference. In this case they should at least know that their owning TaskContext went away.

Fix service destruction

---

rtt/os/Timer.cpp
rtt/os/Timer.hpp
rtt/transports/corba/CorbaDispatcher.hpp

Port of some patches from https://github.com/snrkiwi/rtt/tree/rdt-next to fix compile errors after https://github.com/orocos-toolchain/ocl/pull/59 has been merged.

Improved naming of timer threads

---

rtt/Logger.cpp

just call clear() will not reset the stringstream. And the log will not append to the stringsteam before reset the flag.
reflink: http://stackoverflow.com/questions/2848087/how-to-clear-stringstream

rtt Logger: clear any fail and eof flags

---

rtt/Property.hpp
rtt/PropertyBag.cpp
rtt/base/PropertyBase.hpp

Following my suggestion in #158, this patch removes the `RTT::base::PropertyBase::copy()` method and introduces
[PropertyBag assignment](https://github.com/orocos-toolchain/rtt/blob/953c0ec5960cf148ed78b784a5767b78c5254044/rtt/PropertyBag.cpp#L227) is supposed to have linking semantics (changing the value of a property in the copy also changes the value in the original bag), which is important for property composition and decomposition.
The `PropertyBase::copy()` method introduced in 44b9970e9685b9b812ddce1e8cc8c9b400553d54 had this linking semantics and was used for PropertyBag assignment, but the term `copy` was actually always associated with deep-copy semantics in RTT, like in PropertyBase::copy(const PropertyBase *) or in DataSourceBase::copy().
This patch introduces an alternative …

property: remove copy() method and allow to construct or create a property with a custom data source

---

rtt/CMakeLists.txt
rtt/os/gnulinux/fosi.h
rtt/os/tlsf/Changelog
rtt/os/tlsf/README
rtt/os/tlsf/TODO
rtt/os/tlsf/tlsf.c
rtt/os/tlsf/tlsf.h

Port of some patches from https://github.com/snrkiwi/rtt/tree/rdt-next to fix compile errors after https://github.com/orocos-toolchain/ocl/pull/57 has been merged.
The patches are mainly required for debugging TLSF memory issues.

TLSF upgrade and debugging

---

rtt/extras/TimerThread.cpp

This was probably forgotten in e013a1ff that introduced CPU affinity of threads.

TimerThread: do not return the same instance if CPU affinity differs

---

rtt/deployment/ComponentLoader.cpp
rtt/deployment/ComponentLoader.hpp
rtt/transports/corba/TaskContextProxy.cpp
rtt/transports/corba/TaskContextProxy.hpp

#66 introduced aliases for CORBA component servers and added an optional name argument to `ComponentLoader::unloadComponent(tc)` in bf92dcb3483f89ccb436502e1f74a04361e53c74. This change has been reverted, because it could lead to inconsistencies in the internal component map, if a TaskContext is destroyed based on the given name but with an unrelated instance pointer.
This concern has initially be brought up as a comment in https://github.com/orocos-toolchain/rtt/commit/bf92dcb3483f89ccb436502e1f74a04361e53c74.
The new approach should be safe as it does not rely on the name or alias of the instance to be unloaded at all.

Corba aliases: revert API changes and fixed ComponentLoader::unloadComponent() for aliased components

---

rtt/transports/corba/RTTCorbaConversion.hpp
rtt/transports/corba/ServiceRequesterI.cpp

1. Compiler warning and uncaught exception in `CServiceRequester::connectCallerTo()`:
`COperationInterface::getArity(name)` always returns an unsigned value and throws an exception if the operation with the given name does not exist.
```cpp
ServiceRequesterI.cpp:164:39: warning: comparison is always false due to limited range of data type [-Wtype-limits]
```
2. unused-but-set-parameter warning in `AnyConversion<std::string>::toCorbaType()`
This non-templated overload of the method is not different from the template method, so can be removed. Note that type `T` in the templated variant always needs to have reference semantics, which is the case when called from `AnyConversion<std::vector<std::string>>::toCorbaType()` in [CorbaConversion.hpp:237](https://github.com/meyerj/rtt/blob/efef0ad33e …

Fix some compiler warnings in the CORBA plugin

---

rtt/deployment/ComponentLoader.cpp

This while loop never terminates if there is more than one component loaded. Ouch!

Fixed bug in component unloading.

---

rtt/internal/FusedFunctorDataSource.hpp
rtt/transports/corba/OperationInterfaceI.cpp
rtt/transports/corba/OperationInterfaceI.h

Follow-up of #134, which reverted a patch introduced in #90 for loading global service plugins into an Orocos process from remote peers, which is required for the RTT introspection feature. As far as I know this use case has not yet been solved or worked around differently. @jmachowinski?
From https://github.com/orocos-toolchain/rtt/pull/134#issuecomment-280730858:
> The second approach is probably more feasible and similar to the operation you added to the TaskContext interface, but I would only expose the access to PluginLoader::loadPlugin() (or all global services) in TaskContextProxy instances and not for every local TaskContext. And it would not break existing code that already uses the loadPlugin(...) operation on the remote side.
From …

Allow loading of global service plugins via the CORBA interface of each TaskContextProxy

---

env-hooks/00.rtt.sh.in

in a zsh environment $path is the same as $PATH. So having this package
installed and sourcing ROS screws up everything.
Fixes #225

use another variable name for CMAKE_PREFIX_PATH entries

---

rtt/transports/corba/ServiceI.cpp
rtt/transports/corba/ServiceI.h

The CORBA layer should not delay the destruction of Service instances once the owning TaskContext gets destroyed. Accessing a destroyed service instance through CORBA would result in a bad_weak_ptr exception now which is handled by the CORBA implementation, but does not cause a segfault.

corba: manage links to Service instances in weak pointers

---

rtt/types/TypeInfoRepository.cpp
tests/types_test.cpp

The type name aliases registered in the TypeInfo are currently unused within RTT and OCL. This commit allows to lookup TypeInfo pointers via an alias, e.g. in Orocos scripting. Not sure what they have been used for before.
Cherry-picked, slightly modified and reopened from https://github.com/meyerj/rtt/pull/5.

Fix/add TypeInfo retrieval by alias name

---

rtt/Logger.hpp
rtt/Logger.inl

This pull request is part of a bigger effort to add support for new connection semantics to RTT (see #114).
There is not much to be said about this one. The const reference variant is more efficient when the RTT::Logger is used for instances of complex data types that implement their own streaming operators.

logger: use const reference for templated streaming operator

---

rtt/internal/DataSource.hpp
rtt/internal/DataSources.hpp
rtt/internal/DataSources.inl
rtt/rt_string.cpp
rtt/rt_string.hpp
rtt/rtt-config.h.in
rtt/typekit/RTTTypes.hpp
rtt/typekit/Types.hpp
rtt/typekit/Types.inc

This patch has already been merged into [toolchain-2.9](https://github.com/orocos-toolchain/rtt/tree/toolchain-2.9) in 6ccb412fe4e6a51751b35f497fe6abbebd2d0930 at May 2016 and I am not aware of any problems so far, but there was never a pull request and it might be worth to document and discuss.
This is for consistency reasons and to avoid duplicate code generation. The RTT core already uses various bool and std::string data sources internally and hence already has instantiations of these template classes. This patch adds extern template declarations to the `DataSource.hpp` and `DataSources.hpp` headers and removes them from the typekit headers.
Also the instantiation of the `rt_string` and `rt_ostringstream` classes (not of the respective RTT template instantiations) have been moved from …

Moved instantiation of DataSource template types for bool and std::string from the typekit to the core library

---

tests/taskstates_test.cpp

...in order to fix build errors on Travis: https://travis-ci.org/orocos-toolchain/rtt/builds/301599579
New build was successful: https://travis-ci.org/orocos-toolchain/rtt/builds/301622937
These new test cases have been added in 5247e72d as part of https://github.com/orocos-toolchain/rtt/pull/182.

tests: make taskstates_test more robust against slow execution

---

rtt/OperationCaller.hpp
rtt/Service.hpp
rtt/base/OperationCallerInterface.hpp
rtt/internal/DataSourceStorage.hpp
rtt/internal/OperationCallerC.cpp
rtt/internal/OperationCallerC.hpp
rtt/internal/RemoteOperationCaller.hpp
tests/operations_fixture.hpp
tests/operations_fixture1.cpp
tests/remote_method_test.cpp

This bugfix affects all OperationCallers where the signature does not exactly match the operation's signature. In this case `RTT::OperationCaller<Signature>` falls back to an `RemoteOperationCaller<Signature>` implementation, which is able to adapt argument or return types if the exact types or qualifiers do not match.
Without this patch it was not possible to set the caller engine of such an operation caller after the initial construction because it did not reimplement the [OperationCallerInterface::setCaller()](https://orocos-toolchain.github.io/rtt/master/api/html/structRTT_1_1base_1_1OperationCallerInterface.html#adb68aecd6596ce7e6760dd5e3da999e2) method, but stored the original caller inside the `OperationCallerC` instance stored in the `mmeth` member variable. As a consequence …

Fix setting the caller engine for RemoteOperationCaller instances

---

rtt/os/gnulinux/fosi_internal.cpp
tests/tasks_test.cpp

A patch contributed by @snrkiwi:
The algorithm currently takes only the last 15 characters of the activity's name. With long component/activity names this can easily result in the same name for multiple components. This is exacerbated in CORBA dispatchers which append "Corba" on the end of the activity's name, thus reducing the usable name size to 10 characters. So any component names that end in "Configuration" will all have the same thread name, "figurationCorba", rendering them unidentifiable.
A compromise solution is to take the first 7 char's of the name, and the last 7 char's of the name, and put the `"~"` char between them. Now components like `"RobotConfiguration"` and `"MyConfiguration"` become `"RobotCon~uration"` and `"MyConfiguration"` respectively, and their CORBA dispatchers …

os: Change thread name compaction algorithm to produce more readable results

---

rtt/base/DataObjectLockFree.hpp

`oro_atomic_t` is a plain old data struct with a volatile int member. It is initialized by `oro_atomic_set()` and does not need an initializer.
This fixes an `anachronistic old-style base class initializer [-fpermissive]` compiler error with gcc-4.9 in Debian Jessie for the xenomai target.

fixed wrong initialization of oro_atomic_t members in DataObjectLockFree<T>::DataBuf constructor

---

tests/tasks_test.cpp

The condition to execute that part was always evaluating to false because it compared a scheduler type with a priority. The actual test case is invalid because even for a real-time thread with the highest priority there is no guarantee that it executes at least once between the start and stop call.
@snrkiwi You added this test case in 2011. Is this something you would expect from RTT? Maybe the test would have worked back then, but a later update changed the behavior of  `start()` in this case and this was not detected due to the wrong comparison?

tests: removed special case for high-priority real-time threads in testAffinity

---

rtt/internal/Collect.hpp
rtt/internal/CollectSignature.hpp

`collectIfDone(...)` was calling `cimpl->collect(...)` for the specializations with more than three arguments.
Also reordered template specializations in `Collect.hpp`.
This is a nasty one.

Fix collectIfDone() for more than three arguments

---

rtt/os/gnulinux/fosi.h
rtt/os/gnulinux/fosi_internal.cpp

This PR applies the patch proposed by @rbrtslmn in #105.
It switches to use a monotonic clock source for periodic waiting in the gnulinux target, but it is also somehow incomplete because it does not fix the same issue for other broken targets (like MacOS), for waiting on condition variables and for RTT Timers.

gnulinux: use CLOCK_MONOTONIC for periodic tasks (fix #105)

---

rtt/transports/mqueue/binary_data_archive.hpp
rtt/types/carray.hpp
rtt/types/type_discovery.hpp
tests/mqueue_archive_test.cpp

`boost::serialization::array<T>` has been renamed to `array_wrapper<T>` in Boost 1.61. Its usage in RTT has been adapted in https://github.com/orocos-toolchain/rtt/commit/87659188c71bf3013247590a386321648dd8fb67 with a follow-up in https://github.com/orocos-toolchain/rtt/commit/0d83c908a6f06934cbf6b872537a49edcaf730fd (https://github.com/orocos-toolchain/rtt/pull/192).
The respective header has also been renamed to `array_wrapper.hpp` in Boost 1.64 and starting from 1.65 [array.hpp](https://github.com/boostorg/serialization/blob/boost-1.65.0/include/boost/serialization/array.hpp#L26) includes [array_wrapper.hpp](https://github.com/boostorg/serialization/blob/boost-1.65.0/include/boost/serialization/array_wrapper.hpp) (https://github.com/boostorg/serialization/commit/1d86261581230e2dc5d617a …

Fix compilation error with Boost 1.64

---

rtt/os/gnulinux/fosi.h

Minor bug in the code to initialize a recursive mutex for the `gnulinux` target, an oversight in https://github.com/orocos-toolchain/rtt/pull/258/commits/67e1a101c7cfa14068cf94cefe20fb6ecbe6ec11#diff-39403cc75fc553eb965d446766e58f07R204. Not critical because at least on common platforms it is unlikely that
```cpp
pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_RECURSIVE_NP)
```
ever returns with a non-zero value (`EINVAL`) ([man](https://linux.die.net/man/3/pthread_mutexattr_settype)).

os/gnulinux: fix return value of pthread_mutexattr_settype in rtos_mutex_rec_init()

---

.travis.yml
tests/corba_ipc_test.cpp
tests/taskthread_fd_test.cpp

Unit tests on [Travis CI](https://travis-ci.org/orocos-toolchain/rtt) occasionally fail for no good reason, especially for branches and pull requests based on [toolchain-2.9](https://github.com/orocos-toolchain/rtt/tree/toolchain-2.9):
- https://travis-ci.org/orocos-toolchain/rtt/builds/406025524
- https://travis-ci.org/orocos-toolchain/rtt/builds/395411220
This pull request...
- disables the `testFileDescriptor_Timeout` test case for Travis (based on the `CI` environment variable) which has timing requirements Travis cannot always satisfy.
- enables OmniORB exception tracing such that they are printed to the console (instead of a generic "unknown location/unknown type" error message). The `giopStream::CommFailure` exceptions can occur during cleanup of the `corba-ipc-test` (to be …

Another attempt to fix flaky unit tests at Travis

---

tests/taskstates_test.cpp
tests/taskthread_test.cpp

- Calls to usleep from a SCHED_FIFO thread triggers the context switch signal handler. Use `rtos_nanosleep()` instead.
- CPU affinitiy can only be set when a thread is created with xenomai, but `getCPUAffinity()` returns `~0` unconditionally. TimerThread ignores the CPU affinity if `getCPUAffinity()` is not supported for the respective target and the test case would fail.
- `Thread::getPid()` and `rtos_task_get_pid()` are not supported in Xenomai either.

tests: fixed some newer unit tests for the xenomai target (Xenomai 2)

---

rtt/RTT.hpp
rtt/internal/OperationCallerC.cpp
rtt/internal/SendHandleC.cpp
rtt/marsh/TinyDemarshaller.cpp
rtt/scripting/StatementProcessor.cpp
rtt/transports/corba/corba.h

https://github.com/orocos-toolchain/rtt/commit/b6344416a45887f61af37061b29045e5a1d3cc3d revealed that some classes are implemented in the `RTT` namespace directly while they are defined in a nested namespace, like `RTT::marsh` or `RTT::internal`.
Foreign namespaces should be excluded from API documentation, like `boost::serialization` or `CORBA`.

Fix namespace of some definitions and exclude unrelated namespaces from API documentation

---

orocos-rtt-config.cmake

If the RTT cmake module is used more than once with different components and the `REQUIRED` argument was not given during the first invocation, a second invocation with `REQUIRED` might trigger false errors because of items added to `MISSING_COMPONENTS` earlier.
Example:
```cmake
find_package(Orocos-RTT COMPONENTS non-existent-plugin)      # not available
if(OROCOS-RTT_NON-EXISTENT-PLUGIN_FOUND)
endif()
find_package(Orocos-RTT REQUIRED COMPONENTS rtt-scripting)   # I really need scripting!
```
prints
```cmake
-- - Detected OROCOS_TARGET environment variable. Using: gnulinux
-- Orocos-RTT found in /opt/orocos/kinetic/install_debug/lib/cmake/orocos-rtt/orocos-rtt-gnulinux-libraries.cmake
-- Found orocos-rtt  for the gnulinux target. Available transports: corba mqueue
-- - Detected …
```

cmake: unset found and missing components list after each invocation of the RTT cmake config

---

rtt/TaskContext.cpp

Fix null pointer exception that was generated only if the following conditions were met:
- `ORO_ACT_DEFAULT_SEQUENTIAL` not defined
- `ORO_ACT_DEFAULT_ACTIVITY` not defined
- `new_act == 0`
@meyerj PTAL

rtt: fix null ptr exception in RTT::TaskContext::setActivity

---

UseOROCOS-RTT-helpers.cmake
UseOROCOS-RTT.cmake

This pull requests solves the problem that if a package `b` is installed in the same folder than RTT or another package `a` which is used by `b`, the include directories of the shared install-space have been added to the compiler command line before the package-local include directories specified with `include_directories()`. This is typically the case if a catkin workspace is built with `catkin_make_isolated --install`. As a consequence of this, the install-space has to be cleaned before rebuilding whenever a header in the source folder has been changed.
Example CMakeLists.txt:
``` cmake
project(b)
find_package(Orocos-RTT REQUIRED)
include(${OROCOS-RTT_USE_FILE})
orocos_use_package(a)
include_directories(include/headers/of/b)
orocos_library(b_library src/b.cpp) …
```

Configuration of Orocos include directories and definitions per target instead of per directory

---

rtt/scripting/StateMachine.cpp
rtt/types/TypeInfoRepository.cpp
tests/corba_test.cpp
tests/operations_fixture.cpp
tests/service_test.cpp
tests/state_test.cpp

This PR contains a subset of the patches in #135, that only fix bugs and do not change the execution semantics of Orocos state machines. We consider to only include those in the 2.9 release but not yet the new execution logic.
167076a68ced2fad11a0998ef4df76ade1b31200 solves an issue where the entry program of a state can be aborted by an event in some cases. dc1b39b86334ac0a6a897590dce689b8195e7ccd removes a duplicate call to `enableEvents()`, which would trigger an assert if RTT is compiled in debug mode. The other two are minor patches for the unit tests.

State machine bug fixes

---

rtt/plugin/PluginLoader.cpp

Originally reported in orocos-toolchain/ocl#40.
To reproduce:
```
$ deployer
import("rtt_rosdeployment")
require("rosdeployment")
```
The problem is that `createService()` returns a null pointer in [rtt_rosdeployment_service.cpp](https://github.com/orocos/rtt_ros_integration/blob/indigo-devel/rtt_rosdeployment/src/rtt_rosdeployment_service.cpp) and the PluginLoader did not catch this case before forwarding it to `Service::addService()`.

pluginloader: fixed segfault if a service plugin refuses to create a service instance to be loaded into the global service

---

UseOROCOS-RTT.cmake

CMake target importing and exporting [1] is an alternative way to find and link to targets that have been generated and installed from another package in case users do not want to rely on the `orocos_generate_package()` and `orocos_use_package()` macros provided by UseOROCOS-RTT.cmake. This PR supports this workflow by adding an EXPORT argument to the macros that create Orocos targets and by exporting all targets under the export name `${PROJECT_NAME}-${OROCOS_TARGET}` by default.
[1] https://cmake.org/Wiki/CMake/Tutorials/Exporting_and_Importing_Targets#Exporting_from_an_Installation_Tree

useorocos: added optional macro argument EXPORT and export cmake target names for all target types

---

rtt/ConnPolicy.cpp
rtt/ConnPolicy.hpp
rtt/typekit/RealTimeTypekitTypes2.cpp

This patch is a backport of the streaming operator added in [#118](https://github.com/orocos-toolchain/rtt/pull/118/files#diff-b45975d85b48882bab76083ed4efd886R263).
It is required to fix build errors with some newer unit tests that have originally been written for `toolchain-2.9`, e.g. the unit test added in #281.

Add ostream operator for RTT::ConnPolicy

---

rtt/deployment/ComponentLoader.cpp

Change component loader behaviour to consider a component found on first valid path

---

rtt/base/ChannelInterface.cpp
rtt/base/InputPortInterface.cpp
rtt/base/OutputPortInterface.cpp
rtt/base/PortInterface.hpp
rtt/internal/ConnFactory.cpp
rtt/internal/ConnFactory.hpp
rtt/internal/ConnInputEndPoint.hpp
rtt/internal/ConnOutputEndPoint.hpp
rtt/internal/ConnectionManager.cpp
rtt/internal/ConnectionManager.hpp
rtt/internal/PortConnectionLock.hpp
rtt/internal/rtt-internal-fwd.hpp
tests/ports_test.cpp

The `connection_mutex` owned by the port's `ConnectionManager` was only protecting its internal list of connections, but not the whole process of creating new connections, data objects or buffers. At least connections that involve shared buffers (#114) were subject to race conditions if multiple threads establish and disconnect connections concurrently.
The new port connection mutex is locked early inside the `ConnFactory` and inside `ConnInputEndPoint` and `ConnInputEndPoint` for the case port connection is disconnected from the remote end.
`InputPortInterface::connected()` and `OutputPortInterface::connected()` are forwarding to their respective ChannelElement endpoints, where the test can be done in lock-free way.
The `ports_test` has been updated to also cover errors during concurrent …

Introduce a mutex owned by each port that protects its connections

---

rtt/os/CAS.hpp
rtt/os/Mutex.hpp
rtt/os/MutexLock.hpp
rtt/os/oro_arch_interface.h
rtt/os/oro_gcc/oro_arch.h
rtt/os/oro_i386/oro_arch.h
rtt/os/oro_noasm/oro_arch.h
rtt/os/oro_x86_64/oro_arch.h
rtt/os/rtt-os-fwd.hpp

This pull request is part of a bigger effort to add support for new connection semantics to RTT (see #114).
The new mutex type implements a shared ownership lock that allows concurrent access to shared data by multiple readers and exclusive access for writers. This lock type is used to protect the input and output pointers lists in the new `ChannelElementBase` implementations.
The concept of a shared mutex is targeted to be added to the C++ standard library sooner or later as [std::shared_mutex](http://en.cppreference.com/w/cpp/thread/shared_mutex) and provided by the Boost thread library as [boost::shared_mutex](http://www.boost.org/doc/libs/1_54_0/doc/html/thread/synchronization.html#thread.synchronization.locks.shared_lock).

Added new mutex class SharedMutex which implements a shared lock ownership mode

---

rtt/base/BufferBase.hpp
rtt/base/BufferInterface.hpp
rtt/base/BufferLockFree.hpp
rtt/base/BufferLocked.hpp
rtt/base/BufferUnSync.hpp
rtt/base/DataObjectBase.cpp
rtt/base/DataObjectBase.hpp
rtt/base/DataObjectInterface.hpp
rtt/base/DataObjectLockFree.hpp
rtt/base/DataObjectLocked.hpp
rtt/base/DataObjectUnSync.hpp
rtt/internal/AtomicMWMRQueue.hpp
rtt/internal/AtomicMWSRQueue.hpp
rtt/internal/AtomicQueue.hpp
rtt/internal/ChannelBufferElement.hpp
rtt/internal/ChannelDataElement.hpp
rtt/internal/ConnFactory.hpp
tests/buffers_test.cpp
tests/ports_test.cpp

This pull request is part of a bigger effort to add support for new connection semantics to RTT (see #114).
- Moved storage of the `FlowStatus` to the `DataObjectInterface` or `BufferInterface` implementations instead as unprotected member variables of `ChannelDataElement`
- Decide whether to use an `AtomicMWMRQueue` (renamed from `AtomicQueue`) or an `AtomicMWSRQueue` in `BufferLockFree` depending on whether the buffer is circular or must support multiple reader threads.
For a circular buffer also the writer thread may consume elements if the buffer is full, so the queue has to support multiple readers. This was broken in previous versions of RTT v2 and could lead to buffer corruption on concurrent writer/reader access.
- Added a boolean return value to `DataObjectInterface::Set()` in …

Fixed FlowStatus race condition in ChannelDataElement and fixed BufferLockFree implementation for the circular buffer case

---

rtt/deployment/ComponentLoader.cpp
rtt/os/xenomai/fosi_internal.cpp
rtt/plugin/PluginLoader.cpp
rtt/rtt-config.h.in
tests/dataflow_performance_test.cpp

...to suppress compiler warnings on unused code elements.
This patch has already been in `toolchain-2.9` for quite a while (https://github.com/orocos-toolchain/rtt/commit/6a4a469100d42526cdfc9c96a924aedeb6f2824e).

rtt-config.h: introduce RTT_UNUSED macro and use it consistently

---

rtt/transports/corba/ServiceI.cpp
rtt/transports/corba/ServiceI.h

Follow-up on #238, but targeting master now:
> The CORBA layer should not delay the destruction of Service instances once the owning TaskContext gets destroyed. Accessing a destroyed service instance through CORBA would result in a bad_weak_ptr exception now which is handled by the CORBA implementation, but does not cause a segfault.
The usage of the `weak_ptr` instances in #238 was actually invalid: The intention was to trigger an exception when dereferencing an expired weak pointer, which is then returned to the caller through the CORBA layer. But [boost::weak_ptr<T>::lock()](https://www.boost.org/doc/libs/1_70_0/libs/smart_ptr/doc/html/smart_ptr.html#weak_ptr_lock) does not throw and might return a null pointer, which would result in a segmentation fault instead. Not better than before …

corba: manage links to Service instances in weak pointers [master]

---

rtt/SendHandle.hpp
rtt/internal/CollectSignature.hpp
rtt/internal/LocalOperationCaller.hpp
rtt/internal/ReturnSignature.hpp

From https://github.com/orocos-toolchain/rtt/commit/ed8401254918465a5613f5f2574c04c1514c95e8 (by @psoetens):
> There was no need to have this non-const. non-const prevented us to use it on a `const&` to a `SendHandle`, which we do need if the `SendHandle` is presented by a `DataSource`.
This commit is part of unmerged https://github.com/orocos-toolchain/rtt/pull/84, but actually independent.

operations: add const qualifier in collect family of functions

---

rtt/os/tlsf/tlsf.c

Fix compiler warnings for discarded return values in tlsf

---

rtt/ExecutionEngine.cpp

Without the added lock of the message mutex it can happen that the calling thread wakes up and checks the completion condition in `waitForMessagesInternal()`, but the runner engine finishes and signals the condition variable in `processFunctions()` before the calling thread enters waiting state again.
This is a race condition and it is hard to catch it in a unit test.
This lock was already introduced in https://github.com/orocos-toolchain/rtt/commit/58cb4bb733fc14de0ca520620cfcb689e2155797 as part of #91, but has been reverted in https://github.com/orocos-toolchain/rtt/commit/b9f2f348959216f32819967d1b49910deeb4bed6 before the merge. There was a comment in https://github.com/psoetens/rtt/pull/3#issuecomment-280170267 that explains why the revert was needed, which also leaves the question …

Fix race condition when waiting for functions

---

rtt/Handle.cpp
rtt/Handle.hpp
rtt/Property.hpp
rtt/PropertyBag.cpp
rtt/PropertyBag.hpp
rtt/SendHandle.hpp
rtt/os/oro_gcc/oro_arch.h
rtt/scripting/parse_exception.hpp
tests/datasource_test.cpp
tests/taskthread_fd_test.cpp
tests/unit.hpp

This pull request eliminates some compiler warnings with newer compilers (GCC 9 in upcoming Ubuntu 20.04, with Boost 1.72). Some warnings are older and already appeared before.
The patch also includes an API update proposal for more consistent copy assignment semantics of `RTT::Property<T>`, which was inconsistent with copy construction, and a slightly modified API of `RTT::PropertyBag` for adding properties, that likely has no effect in practice.

Fix compiler warnings with GCC 9 (with API changes)

---

rtt/Activity.hpp

This sentence was introduced in 06146b6a2c9f05c390113c3ffaf2ceab6d36f616 (#91) due to a wrong understanding of `ORO_WAIT_ABS` and `ORO_WAIT_REL`. The old behavior was restored later in 171a700866a8c03057bec2e5ec59ada4e9f3a8af and 6047c605696280fa14e7c4291a400180cc4faa3b
(https://github.com/Intermodalics/rtt/pull/2), but without updating the class documentation.

Remove wrong statement in the documentation of class RTT::Activity

---

rtt/extras/FileDescriptorActivity.cpp
rtt/extras/FileDescriptorActivity.hpp
tests/specialized_activities.cpp

With the introduction of the work() method, which allowed to
be more precise on what gets called in which condition,
an event port under FileDescriptorActivity would not make
updateHook get called anymore.
This broke the Rock workflow with file descriptor activities.
(Un)fortunately, the effect has been subtle enough to not be
noticed readily. Or people started deploying tasks under the
normal Activity where before it would work with the FDA (I'm
guilty of that).
This is a rather convoluted code path (the characters in the
play are a FileDescriptorActivity 'FDA', ExecutionEngine 'EE'
and a TaskContext 'TC'
- the port signal calls FDA::trigger()
- FDA::trigger() wakes-up the FDA loop, which calls EE::work(Trigger)
- EE::work(Trigger) calls EE::processPortCallbacks but NOT
EE::processHooks …

fix default event port behavior along with FileDescriptorActivity
